version: "3.8"
services:
  db:
    restart: always
    image: postgres:15.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=elxolding
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
