version: '3.8'

services:
  front:
    build:
      context: ./app
      target: prod

  back:
    build:
      context: ./back
      target: prod
    environment:
      NODE_ENV: production
    volumes:
      - ~/volumes/elxolding/postgres:/app/uploads

  db:
    image: postgres:15.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: elxolding
    ports:
      - "5432:5432"
    volumes:
      - ~/volumes/elxolding/postgres:/var/lib/postgresql/data
