version: '3.8'

services:
  front:
    restart: always
    build:
      context: ./app
      target: prod
      args:
        - NUXT_PUBLIC_API_URL=/api

  nginx:
    restart: always
    image: nginx:1.21.3
    build:
      context: ./
      target: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/volumes/elxolding/uploads:/www/media
    ports:
      - "80:80"
    depends_on:
      - back

  back:
    restart: always
    build:
      context: ./back
      target: prod
    environment:
      NODE_ENV: production
    ports:
      - "3030:3030"
    volumes:
      - ~/volumes/elxolding/postgres:/app/uploads
    depends_on:
      - db

  db:
    restart: always
    image: postgres:15.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: elxolding
    ports:
      - "5432:5432"
    volumes:
      - ~/volumes/elxolding/postgres:/var/lib/postgresql/data
