name: Deployment

on:
  push:
    branches: [ staging ]

env:
  DEPLOYMENT_ENV: staging

jobs:
  deploy:
    runs-on: gcidp
    environment: staging
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build and Deploy
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DEPLOYMENT_ENV: staging
          BRANCH_NAME: ${{ github.ref_name }}
          COMMIT_SHA: ${{ github.sha }}
        run: docker compose -f docker-compose.staging.yml up -d --build