name: Build and Deploy

on:
  push:
    branches: [ main, staging ]

env:
  DEPLOYMENT_ENV: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

jobs:
  build:
    runs-on: ${{ github.ref == 'refs/heads/main' && 'self-hosted' || 'gcidp' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: docker compose -f docker-compose.${{ env.DEPLOYMENT_ENV }}.yml up -d --build

      - name: Cleanup
        run: docker system prune -f
